import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.scss'
import {Navbar} from "@/app/UI/NavBar/Navbar";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Шифрование',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="ru" data-lt-installed={true}>
        <body className={inter.className}>
        <Navbar/>
        <div className='container mx-auto p-4'>
            {children}
        </div>
        </body>
        </html>
    )
}
